8 feat add about page
dothidden/writeups pull request #22
Opened 2023-06-08 19:55 UTC by Stefan-Radu

Each of us should update the config with the appropriate details.

2023-06-08 20:36 UTC, Mathis-Dory commented
I will do it now :)

2023-06-09 14:46 UTC, Costinteo commented
@Stefan-Radu you forgot to add your line lol.

2023-06-11 19:51 UTC, Stefan-Radu commented
@Costinteo to link your github xD

2023-06-11 20:25 UTC, Mathis-Dory commented
I added my part, I think @SecioreanuStefanita  you are the last one and then we can merge the PR.

2023-06-20 11:32 UTC, Mathis-Dory approved these changes

2023-06-20 18:12 UTC, Mathis-Dory requested changes

2023-06-20 18:12 UTC, Mathis-Dory commented on config.yaml
> +      picture: https://avatars.githubusercontent.com/u/39965799?v=4
Change it @SecioreanuStefanita

2023-06-20 19:19 UTC, merged